### ISSUE TITLE
EXIF tool  integration

### ISSUE THREAD

**Issue by Artiom-M** [Ribtoks/xpiks#183]
Have you considered using a library instead of external exif tool. This one for example:
http://www.exiv2.org/

The same for curl: http://www.curlpp.org/

**Comment by Ribtoks** [comment]
I definitely wanted to use Curl as a library to get precise upload percentage out from it. Because percentage grabbing while uploading is implemented with a pinch of black magic now.

Regarding exiftool - I don't know, maybe. It definitely works now and i don't see any major profit in moving to library, though I'm absolutely not against it.

**Comment by Artiom-M** [comment]
exif integration will remove the requirement of downloading it and installing manually for Mac OS for example. Small profit, I agree.

**Comment by Ribtoks** [comment]
Fixed in 1.3.1 (after merging `exiv2_integration` branch)
