### ISSUE TITLE
Video support

### ISSUE THREAD

**Issue by ribtoks** [ribtoks/xpiks#248]
metadata should be saved to csv

**Comment by Ribtoks** [comment]
Update procedures after video thumbnail created:

`ArtworksUpdateHub` is Mutex-protected vector of `structs { ArtworkID, LastKnownIndex, GenerationIndex }`. 

If `ArtItemsModel [LastKnownIndex].getID() == ArtworkID` (_i.e. artwork is on it's place_) then artwork will be updated otherwise `GenerationIndex++` and `push_back()` back to `ArworksUpdateHub`.

For those with `GenerationIndex > 1` create a `Set<ArtworkID>` and loop all artworks and check if it's video and in the `Set`.

`ArtworksUpdateHub` can have scheduled 5 seconds timer call to update ArtItemsModel in the main thread.

**Comment by Ribtoks** [comment]
Global scheme

Files added -> video thumbnails requested.

while _thumb_ `NOT_READY` video item returns _StandardVideoThumb_

`CachingImageProvider` returns qrc icon?

`VideoThumbService` -> Thumb generated -> `ImageCachingService` -> Cache image

1st Thumb - Quick
2nd Thumb - "smart" (if we have < 100 videos)

Update VideoArtwork thumb and then update `ArtItemsModel` (comment above)

**Comment by ribtoks** [comment]
Closed in gigantic effort across multiple branches.
