### ISSUE TITLE
Title - Description order in list mode.

### ISSUE THREAD

**Issue by velmafia** [ribtoks/xpiks#524]
Hi,
In "List mode" xpiks have unintuitive order of textboxes (First is Description, Second is Title). More intuitive is  when Title is first (like in "Edit mode").
Also usually title is shorter than description, so i think it's will be nice to change size of this textboxes.

aloha!

**Comment by ribtoks** [comment]
Hi

Yes, maybe it's not logical at the first point, but Description is more important than Title (because there're many microstocks out there which don't have Title at all, but all of them have Description). Therefore in the main view it's shortened to the greatest common divisor between microstocks.

Having fields in main view disbalanced by size will not be nice.

Anyways, reordering will require yet another redesign of the main view which is not quite a priority for now. So closing for now, but may reopen in future.
