### ISSUE TITLE
RecentItemsModel - items are removed in wrong order

### ISSUE THREAD

**Issue by velmafia** [ribtoks/xpiks#614]
`RecentItemsModel` removes old items in the order of addition, not in order of use. 

Example:
I have 6 directory with name: `D1`, `D2`, ..., `D6`.
When I open this directories in sequences:
```
D1, D2, D3, D4, D5, D1, D1, D6
```
I expect that `D1` is still in `Recent directories` list, because I used it recently. But this item was deleted.

--------
To fix this `RecentItemsModel::doPushItem(...)` method should be changed.

Another question:
I guessing that `m_ItemsSet` is for optimization, do we need this? This is quite small collection, so the profit may be unnoticeable, and we have redundant container.

**Comment by ribtoks** [comment]
@velmafia yes, it's not using fair LRU cache, but it should be trivial to fix, because Xpiks already has [LRU cache implementation](https://github.com/ribtoks/xpiks/blob/master/src/xpiks-qt/Common/lrucache.h) (and even 1 more in Tabs Model, but it's "not documented").

Re: `m_ItemsSet` - probably it was for "optimization" or just for simplicity. Btw,`RecentItemsModel` is quite generic, so it's a coincidence that Directories uses limit of `5` and Files use `10`.
