### ISSUE TITLE
Ability to copy selected text directly from "Logs" window

### ISSUE THREAD

**Issue by zhartus** [ribtoks/xpiks#639]
System info: Ubuntu 16.04 amd64, Xpiks 1.5.2.2 (Appimage).

There is no such ability right now, but it will be very handy for easily bug reporting.

**Comment by ribtoks** [comment]
Hi

This is done "by design". The point is if you want to send logs - send the whole file. Many users think they know better which part of the logs to copy when reporting a bug. However, this often leads to delays since in most cases I need the whole file. It contains important initialization logs in the beginning. So, again, please send the whole file when you want to send logs.
