### ISSUE TITLE
Spontaneous metadata cleanup

### ISSUE THREAD

**Issue by zhartus** [ribtoks/xpiks#661]
`System info: Ubuntu 16.04 amd64, Xpiks 1.5.2.2 (Appimage).`

Sometimes there is a spontaneous clearing of all metadata in the file list - all the fields suddenly becomes empty. I have not yet been able to establish what it depends on and in what cases happens. I'm not sure, but maybe it happens sometimes in the process of selecting or deselecting files.  In such cases, only helps selection "Reimport metadata" from menu.

By the way, despite the fact that all the fields are empty, when I try to re-import, I get a warning dialog:
> "You will lose all unsaved changes after reimport. Proceed?"

And this often happens when I close Xpiks and open it again. One such incident has just happened. I attach two log files. The first one was created during the session that was before the problem. The second one was created when I re-run Xpiks and saw empty fields for entering metadata, although they were filled when the program was closed.

1. [xpiks-qt-20042019-105206-687.log](https://github.com/ribtoks/xpiks/files/3100194/xpiks-qt-20042019-105206-687.log)
2. [xpiks-qt-20042019-135258-658.log](https://github.com/ribtoks/xpiks/files/3100195/xpiks-qt-20042019-135258-658.log)

**Comment by ribtoks** [comment]
Thanks for sending the logs. It's not exactly the "cleanup", it's just that your files have nothing saved in them. But more of that later.

How to fix this temporary:
- Install system exiftool (`apt-get install exiftool` or something along those lines)
- Go to Xpiks menu File -> Preferences -> External and in "Exiftool path" enter just "exiftool" or full path like `/usr/local/bin/exiftool` (second option only if you know exact path)
- Now reopen Xpiks and this issue theoretically should not raise again

Why does this happen:
- Due to intricacies of how AppImage works, path that Xpiks uses to find internal exiftool is not valid anymore (of course, this is problem of developer, not user)
- Initially Xpiks is not able to find exiftool because of aforementioned problem and you cannot import keywords that are in the your files. However, Xpiks keeps trying to find exiftool and then probably it finds some other one and imports your metadata (most of which is empty) and overwrites your current metadata. I understand it does not look intuitive, but that is approximately what happens.

Currently I'm closing this issue in favor of #662 that I created to fix that.

**Comment by zhartus** [comment]
Thanks.
Corrected temporary fix instructions for Ubuntu:

Console command to install package with exiftool included:
`sudo apt-get install libimage-exiftool-perl`
...and then enter in preferences:
`/usr/bin/exiftool`
