### ISSUE TITLE
Make vectors first class artworks in Xpiks (without previews)

### ISSUE THREAD

**Issue by ribtoks** [ribtoks/xpiks#683]
Shutterstock is going to deprecate previews and read metadata from EPS only. Xpiks should support metadata editing and uploading for vectors only.

- [x] remove items on detaching vector from vector
- [x] save metadata both to vector and preview in libxpks
- [x] read metadata from vector in libxpks
- [x] consolidate vector&preview metadata in xpiks
- [x] add switch to disable vector IO
- [x] add vector's black preview (no preview) like video has
- [x] generate previews for image cache for vectors correctly
- [x] read metadata from attached previews/vectors as well (maybe as reimport)

**Comment by zhartus** [comment]
For the same reason, on "Advanced" tab in server settings now we need a new checkbox "Upload vectors only" or something like that. Otherwise, now the vector and raster images uploads on Shutterstock as separate entities.

**Comment by ribtoks** [comment]
Algorithm to attach vectors:
1. Create pairs of input vectors&previews and create `vector` items from that
2. Find pairs for all non-paired from step [1]. For each non-paired we can create a pair either from autoattach (search in same directory) or existing file (if it's existing it should be accounted in `ArtworksRepository`
3. Create pairs of items from step [2].
4. For all other items add them as single

**Comment by ribtoks** [comment]
Fix filesize calculation for vectors when reading

**Comment by ribtoks** [comment]
- [ ] remove items on detaching vector from vector
- [ ] save metadata both to vector and preview in libxpks
- [ ] read metadata from vector in libxpks

**Comment by ribtoks** [comment]
@zhartus yes and no. There would be no point in uploading vector without metadata. Currently Xpiks will not be able to save metadata to .eps and .ai files (because Adobe does not follow it's own XMP standard for these files).

**Comment by zhartus** [comment]
@ribtoks well, right now after uploading images to Shutterstock they are duplicated (the vector and raster are loaded separately). Have to manually delete JPEG-s after uploading, this is not very convenient. The same thing for Alamy stock by the way. So I am anyway now updoad vector without metadata on part of the stocks and enter metadata manually. But at the same time additional work is added to remove uploaded JPEG-s. Moreover, on Alamy you can remove JPEG-s only after their approval, this further aggravates the problem. The ability to load only vectors on specified stocks would greatly simplify the work, even despite the need to manually enter the metadata.

**Comment by ribtoks** [comment]
@zhartus Can you check if that works for you https://github.com/ribtoks/xpiks/releases/tag/v1.5.3-08062019 I implemented both vector keywording and correct vector uploading to Shutterstock

**Comment by zhartus** [comment]
@ribtoks I can't check it because there is no linux version on the [mentioned page](https://github.com/ribtoks/xpiks/releases/tag/v1.5.3-08062019). Can you add appimage or deb?

**Comment by ribtoks** [comment]
No I can't do it yet sorry. Linux packaging is always a pain. I will only add it later after everything is settled (bugfixes, translations etc.).

**Comment by velmafia** [comment]
@zhartus what's your operating system? Debian/Ubuntu? 
Later I will try prepare for you binary version.

**Comment by ribtoks** [comment]
Thanks for taking care of it @velmafia !

**Comment by ribtoks** [comment]
@velmafia Just realized that it will **not** work. EPS files IO and upload are only implemented in real libxpks. If I will manage to handle translations today, tomorrow I might try to do it myself. Which Ubuntu is the best as the base image? 16.04 or 18.04?

**Comment by velmafia** [comment]
@zhartus so I will not prepare binary for you...
@ribtoks I don't use ubuntu, but I think newer will be better

**Comment by ribtoks** [comment]
@zhartus I uploaded AppImage for 1.5.3. Please let me know if that works for you.
@velmafia Can you please also try if AppImage works in your Linux distro?

**Comment by zhartus** [comment]
@velmafia Sorry, I could not answer yesterday.
My OS is Ubuntu 16.04 amd64.

@ribtoks I tried to run your AppImage, but I got an error:
`./Xpiks-x86_64.AppImage: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found (required by /tmp/.mount_Xpiks-pJ4Cn2/./lib/libavcodec.so.58)
./Xpiks-x86_64.AppImage: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.27' not found (required by /tmp/.mount_Xpiks-pJ4Cn2/./lib/libavformat.so.58)
./Xpiks-x86_64.AppImage: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /tmp/.mount_Xpiks-pJ4Cn2/./lib/libcrypto.so.1.1)
./Xpiks-x86_64.AppImage: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.27' not found (required by /tmp/.mount_Xpiks-pJ4Cn2/./lib/libgssapi_krb5.so.2)
./Xpiks-x86_64.AppImage: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /tmp/.mount_Xpiks-pJ4Cn2/./lib/libgnutls.so.30)
`

At the same time, version 1.5.2 runs without problems.
I assume that this is due to the fact that you prepared a binary for 18.04 (which is true decision since this is the latest LTS version). I will try to install the required version of GLIBC on my 16.04 and let you know about the results.

**Comment by ribtoks** [comment]
@zhartus yep, I created it on latest LTS (18.04.1 or smth like that).

**Comment by zhartus** [comment]
@ribtoks Update:
Looks like i was right.
Here is a link to the topic that describe the problem and discusses ways to supply support for Ubuntu 16.04 and all further versions:
https://discourse.nixos.org/t/building-an-executable-with-nix-that-can-run-on-ubuntu-16-04/2338
Is it possible to implement this for Xpiks? This may be useful not only for me, since 16.04 is the previous LTS version, which is still supported and used by many users (I am personally plan update my system after the release of the next LTS (20.04)).

**Comment by ribtoks** [comment]
@zhartus  It is definitely not possible to do it now. I spent lots of time to setup 18.04 for Xpiks build environment. I don't have any more time for investigations for Linux. Maybe for some future release.

**Comment by zhartus** [comment]
@ribtoks Ok, thanks. I'll try to handle it by myself.

**Comment by velmafia** [comment]
@ribtoks yes, it's working in my Debian testing (last updated was a few days ago).
@zhartus I know that this is workaround, but if you want only testing this `appimage` you can try install new ubuntu using [Debootstrap](https://wiki.debian.org/Debootstrap) this will install new system (for example Ubuntu 18.04) to one directory, and it's isolated from your local system. Link above is for Debian, but it's similar in ubuntu, simply you need copy-paste a few lines, and wait a moment.

**Comment by ribtoks** [comment]
@velmafia Thanks for trying it out! 
Re: debootstrap. Chroot always have had some limitations and issues. I wouldn't use it on my main workstation/laptop. It's easier (sorted by complexity) 1. not to use Xpiks. 2. upgrade Ubuntu. 3. Virtualbox with link to directory on host system.

**Comment by zhartus** [comment]
@velmafia Thanks for idea.
@ribtoks Yes, I was just thinking about Virtualbox, I will most likely try this option. Thanks again.
