### ISSUE TITLE
After reopen previous edited images from another directory,  Description and Title become empty for first loaded file.

### ISSUE THREAD

**Issue by velmafia** [ribtoks/xpiks#695]
Simplified scenario:

I tagged images in one directory (`working`), and after that I move finished files to another directory (`completed`). Later, when I open `completed` directory, first file is marker as modified, and its "Description" and "Title" fields are empty. The same problem occurs when I rename file that is first (alphabetically) in directory.

Problem is always (and only) with first file loaded to xpiks.

GIF for illustration this bug:
![xpiks-empty-first-image](https://user-images.githubusercontent.com/5277222/58374689-ad164e00-7f42-11e9-9d57-6d9517a99e2a.gif)

logs attached (from current master: afd244945157c19d6df194d110664f673abee16c):
[pixmap-nok.log](https://github.com/ribtoks/xpiks/files/3219754/pixmap-nok.log)
[pixmap-ok.log](https://github.com/ribtoks/xpiks/files/3219755/pixmap-ok.log)

**Comment by ribtoks** [comment]
Looks super weird

**Comment by ribtoks** [comment]
Ok, so what happens is the following:
- Xpiks adds files (initially emtpy) and starts metadata import jobs (from cache + from files with exiftool)
- after empty files are added, `TextEdit::onTextChanged` is called by QML in `MainGrid.qml` which causes `ArtworksListModel::setData()` to be called with empty text
- now there's a race between import of metadata and `setData()`: if metadata is imported first and then `setData()` is called, artwork becomes modified with empty description/title

This issue is solved in QML control `TextInput` which has `onTextEdited` event (which is fired *only* on user input, not on programmatic changes) but I cannot use it since it does not support syntax highlighting.

If you want fix for this to arrive to master faster, you can cherry-pick this commit to master cac1d556, otherwise it will get merged together with my branch

**Comment by velmafia** [comment]
I will prepare pull-request with this cherry-pick, because I'm working with version built by myself from master branch, and this is really frustration behaviour.
